ARENA_SIZE = 1.2 # tasks don't spawn inside of walls, in webots we use 1.1 range + 0.1 reach radius => 1.2 
ROBOT_SPEED = 1/25 #0.05
NUMBER_OF_TYPES = 2#2#1#
ROBOT_COUNTS = [2, 3]#[2,3]#
NUM_ROBOTS = sum(ROBOT_COUNTS)
SPAWN_PROBABILITIES = [1/3, 2/3]#[1]#
TASK_WORK_TIMES = [[3, 9],[5, 1]]#[[3, 7]]#
TASK_COUNT = 10
MAX_WORK_TIME = 120
MAX_SIMULATION_TIME = 180
AVG_TASK_PER_SECOND = (55.0 / (MAX_WORK_TIME*NUM_ROBOTS))

AVG_TASK_TIME = 15
MAX_TASKS_ASSIGNED = 3


